/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as HelpRouteImport } from './routes/help'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWithdrawRouteImport } from './routes/_authenticated/withdraw'
import { Route as AuthenticatedWalletRouteImport } from './routes/_authenticated/wallet'
import { Route as AuthenticatedVaultRouteImport } from './routes/_authenticated/vault'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRewardsRouteImport } from './routes/_authenticated/rewards'
import { Route as AuthenticatedReferralsRouteImport } from './routes/_authenticated/referrals'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedInvestRouteImport } from './routes/_authenticated/invest'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedDailyRouteImport } from './routes/_authenticated/daily'
import { Route as AuthenticatedActivateRouteImport } from './routes/_authenticated/activate'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminTasksRouteImport } from './routes/_authenticated/admin/tasks'
import { Route as AuthenticatedAdminStakingRouteImport } from './routes/_authenticated/admin/staking'
import { Route as AuthenticatedAdminRewardsRouteImport } from './routes/_authenticated/admin/rewards'
import { Route as AuthenticatedAdminOverviewRouteImport } from './routes/_authenticated/admin/overview'
import { Route as AuthenticatedAdminLedgerRouteImport } from './routes/_authenticated/admin/ledger'
import { Route as AuthenticatedAdminInvestRouteImport } from './routes/_authenticated/admin/invest'
import { Route as AuthenticatedAdminEconomyRouteImport } from './routes/_authenticated/admin/economy'
import { Route as AuthenticatedAdminCodesRouteImport } from './routes/_authenticated/admin/codes'
import { Route as AuthenticatedAdminCampaignsRouteImport } from './routes/_authenticated/admin/campaigns'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin/audit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWithdrawRoute = AuthenticatedWithdrawRouteImport.update({
  id: '/withdraw',
  path: '/withdraw',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWalletRoute = AuthenticatedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVaultRoute = AuthenticatedVaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRewardsRoute = AuthenticatedRewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReferralsRoute = AuthenticatedReferralsRouteImport.update({
  id: '/referrals',
  path: '/referrals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInvestRoute = AuthenticatedInvestRouteImport.update({
  id: '/invest',
  path: '/invest',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDailyRoute = AuthenticatedDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivateRoute = AuthenticatedActivateRouteImport.update({
  id: '/activate',
  path: '/activate',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminTasksRoute = AuthenticatedAdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminStakingRoute =
  AuthenticatedAdminStakingRouteImport.update({
    id: '/staking',
    path: '/staking',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRewardsRoute =
  AuthenticatedAdminRewardsRouteImport.update({
    id: '/rewards',
    path: '/rewards',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminOverviewRoute =
  AuthenticatedAdminOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLedgerRoute =
  AuthenticatedAdminLedgerRouteImport.update({
    id: '/ledger',
    path: '/ledger',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminInvestRoute =
  AuthenticatedAdminInvestRouteImport.update({
    id: '/invest',
    path: '/invest',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEconomyRoute =
  AuthenticatedAdminEconomyRouteImport.update({
    id: '/economy',
    path: '/economy',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCodesRoute = AuthenticatedAdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminCampaignsRoute =
  AuthenticatedAdminCampaignsRouteImport.update({
    id: '/campaigns',
    path: '/campaigns',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/activate': typeof AuthenticatedActivateRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invest': typeof AuthenticatedInvestRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/economy': typeof AuthenticatedAdminEconomyRoute
  '/admin/invest': typeof AuthenticatedAdminInvestRoute
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/staking': typeof AuthenticatedAdminStakingRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/activate': typeof AuthenticatedActivateRoute
  '/daily': typeof AuthenticatedDailyRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/invest': typeof AuthenticatedInvestRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/referrals': typeof AuthenticatedReferralsRoute
  '/rewards': typeof AuthenticatedRewardsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/vault': typeof AuthenticatedVaultRoute
  '/wallet': typeof AuthenticatedWalletRoute
  '/withdraw': typeof AuthenticatedWithdrawRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/admin/economy': typeof AuthenticatedAdminEconomyRoute
  '/admin/invest': typeof AuthenticatedAdminInvestRoute
  '/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/admin/staking': typeof AuthenticatedAdminStakingRoute
  '/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/help': typeof HelpRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/activate': typeof AuthenticatedActivateRoute
  '/_authenticated/daily': typeof AuthenticatedDailyRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/invest': typeof AuthenticatedInvestRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/referrals': typeof AuthenticatedReferralsRoute
  '/_authenticated/rewards': typeof AuthenticatedRewardsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/vault': typeof AuthenticatedVaultRoute
  '/_authenticated/wallet': typeof AuthenticatedWalletRoute
  '/_authenticated/withdraw': typeof AuthenticatedWithdrawRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/campaigns': typeof AuthenticatedAdminCampaignsRoute
  '/_authenticated/admin/codes': typeof AuthenticatedAdminCodesRoute
  '/_authenticated/admin/economy': typeof AuthenticatedAdminEconomyRoute
  '/_authenticated/admin/invest': typeof AuthenticatedAdminInvestRoute
  '/_authenticated/admin/ledger': typeof AuthenticatedAdminLedgerRoute
  '/_authenticated/admin/overview': typeof AuthenticatedAdminOverviewRoute
  '/_authenticated/admin/rewards': typeof AuthenticatedAdminRewardsRoute
  '/_authenticated/admin/staking': typeof AuthenticatedAdminStakingRoute
  '/_authenticated/admin/tasks': typeof AuthenticatedAdminTasksRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/help'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/activate'
    | '/daily'
    | '/dashboard'
    | '/invest'
    | '/notifications'
    | '/profile'
    | '/referrals'
    | '/rewards'
    | '/settings'
    | '/vault'
    | '/wallet'
    | '/withdraw'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/codes'
    | '/admin/economy'
    | '/admin/invest'
    | '/admin/ledger'
    | '/admin/overview'
    | '/admin/rewards'
    | '/admin/staking'
    | '/admin/tasks'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/help'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/admin'
    | '/activate'
    | '/daily'
    | '/dashboard'
    | '/invest'
    | '/notifications'
    | '/profile'
    | '/referrals'
    | '/rewards'
    | '/settings'
    | '/vault'
    | '/wallet'
    | '/withdraw'
    | '/admin/audit'
    | '/admin/campaigns'
    | '/admin/codes'
    | '/admin/economy'
    | '/admin/invest'
    | '/admin/ledger'
    | '/admin/overview'
    | '/admin/rewards'
    | '/admin/staking'
    | '/admin/tasks'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/help'
    | '/privacy'
    | '/reset-password'
    | '/sitemap.xml'
    | '/terms'
    | '/_authenticated/admin'
    | '/_authenticated/activate'
    | '/_authenticated/daily'
    | '/_authenticated/dashboard'
    | '/_authenticated/invest'
    | '/_authenticated/notifications'
    | '/_authenticated/profile'
    | '/_authenticated/referrals'
    | '/_authenticated/rewards'
    | '/_authenticated/settings'
    | '/_authenticated/vault'
    | '/_authenticated/wallet'
    | '/_authenticated/withdraw'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/campaigns'
    | '/_authenticated/admin/codes'
    | '/_authenticated/admin/economy'
    | '/_authenticated/admin/invest'
    | '/_authenticated/admin/ledger'
    | '/_authenticated/admin/overview'
    | '/_authenticated/admin/rewards'
    | '/_authenticated/admin/staking'
    | '/_authenticated/admin/tasks'
    | '/_authenticated/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  HelpRoute: typeof HelpRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/withdraw': {
      id: '/_authenticated/withdraw'
      path: '/withdraw'
      fullPath: '/withdraw'
      preLoaderRoute: typeof AuthenticatedWithdrawRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wallet': {
      id: '/_authenticated/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthenticatedWalletRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vault': {
      id: '/_authenticated/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof AuthenticatedVaultRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rewards': {
      id: '/_authenticated/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof AuthenticatedRewardsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/referrals': {
      id: '/_authenticated/referrals'
      path: '/referrals'
      fullPath: '/referrals'
      preLoaderRoute: typeof AuthenticatedReferralsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invest': {
      id: '/_authenticated/invest'
      path: '/invest'
      fullPath: '/invest'
      preLoaderRoute: typeof AuthenticatedInvestRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/daily': {
      id: '/_authenticated/daily'
      path: '/daily'
      fullPath: '/daily'
      preLoaderRoute: typeof AuthenticatedDailyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activate': {
      id: '/_authenticated/activate'
      path: '/activate'
      fullPath: '/activate'
      preLoaderRoute: typeof AuthenticatedActivateRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/tasks': {
      id: '/_authenticated/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AuthenticatedAdminTasksRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/staking': {
      id: '/_authenticated/admin/staking'
      path: '/staking'
      fullPath: '/admin/staking'
      preLoaderRoute: typeof AuthenticatedAdminStakingRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/rewards': {
      id: '/_authenticated/admin/rewards'
      path: '/rewards'
      fullPath: '/admin/rewards'
      preLoaderRoute: typeof AuthenticatedAdminRewardsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/overview': {
      id: '/_authenticated/admin/overview'
      path: '/overview'
      fullPath: '/admin/overview'
      preLoaderRoute: typeof AuthenticatedAdminOverviewRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/ledger': {
      id: '/_authenticated/admin/ledger'
      path: '/ledger'
      fullPath: '/admin/ledger'
      preLoaderRoute: typeof AuthenticatedAdminLedgerRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/invest': {
      id: '/_authenticated/admin/invest'
      path: '/invest'
      fullPath: '/admin/invest'
      preLoaderRoute: typeof AuthenticatedAdminInvestRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/economy': {
      id: '/_authenticated/admin/economy'
      path: '/economy'
      fullPath: '/admin/economy'
      preLoaderRoute: typeof AuthenticatedAdminEconomyRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/codes': {
      id: '/_authenticated/admin/codes'
      path: '/codes'
      fullPath: '/admin/codes'
      preLoaderRoute: typeof AuthenticatedAdminCodesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/campaigns': {
      id: '/_authenticated/admin/campaigns'
      path: '/campaigns'
      fullPath: '/admin/campaigns'
      preLoaderRoute: typeof AuthenticatedAdminCampaignsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminCampaignsRoute: typeof AuthenticatedAdminCampaignsRoute
  AuthenticatedAdminCodesRoute: typeof AuthenticatedAdminCodesRoute
  AuthenticatedAdminEconomyRoute: typeof AuthenticatedAdminEconomyRoute
  AuthenticatedAdminInvestRoute: typeof AuthenticatedAdminInvestRoute
  AuthenticatedAdminLedgerRoute: typeof AuthenticatedAdminLedgerRoute
  AuthenticatedAdminOverviewRoute: typeof AuthenticatedAdminOverviewRoute
  AuthenticatedAdminRewardsRoute: typeof AuthenticatedAdminRewardsRoute
  AuthenticatedAdminStakingRoute: typeof AuthenticatedAdminStakingRoute
  AuthenticatedAdminTasksRoute: typeof AuthenticatedAdminTasksRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
    AuthenticatedAdminCampaignsRoute: AuthenticatedAdminCampaignsRoute,
    AuthenticatedAdminCodesRoute: AuthenticatedAdminCodesRoute,
    AuthenticatedAdminEconomyRoute: AuthenticatedAdminEconomyRoute,
    AuthenticatedAdminInvestRoute: AuthenticatedAdminInvestRoute,
    AuthenticatedAdminLedgerRoute: AuthenticatedAdminLedgerRoute,
    AuthenticatedAdminOverviewRoute: AuthenticatedAdminOverviewRoute,
    AuthenticatedAdminRewardsRoute: AuthenticatedAdminRewardsRoute,
    AuthenticatedAdminStakingRoute: AuthenticatedAdminStakingRoute,
    AuthenticatedAdminTasksRoute: AuthenticatedAdminTasksRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedActivateRoute: typeof AuthenticatedActivateRoute
  AuthenticatedDailyRoute: typeof AuthenticatedDailyRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedInvestRoute: typeof AuthenticatedInvestRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReferralsRoute: typeof AuthenticatedReferralsRoute
  AuthenticatedRewardsRoute: typeof AuthenticatedRewardsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedVaultRoute: typeof AuthenticatedVaultRoute
  AuthenticatedWalletRoute: typeof AuthenticatedWalletRoute
  AuthenticatedWithdrawRoute: typeof AuthenticatedWithdrawRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedActivateRoute: AuthenticatedActivateRoute,
  AuthenticatedDailyRoute: AuthenticatedDailyRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedInvestRoute: AuthenticatedInvestRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReferralsRoute: AuthenticatedReferralsRoute,
  AuthenticatedRewardsRoute: AuthenticatedRewardsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedVaultRoute: AuthenticatedVaultRoute,
  AuthenticatedWalletRoute: AuthenticatedWalletRoute,
  AuthenticatedWithdrawRoute: AuthenticatedWithdrawRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  HelpRoute: HelpRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
